# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-26 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legajo', models.IntegerField()),
                ('nombre', models.CharField(max_length=140)),
                ('ingreso', models.TimeField(verbose_name='Horario de ingreso')),
                ('egreso', models.TimeField(verbose_name='Horario de egreso')),
            ],
        ),
    ]
