# Generated by Django 2.1.3 on 2018-12-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faceDetection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.IntegerField()),
                ('nombre', models.CharField(max_length=140)),
                ('empresa', models.CharField(max_length=140)),
                ('ingreso', models.TimeField(verbose_name='Horario de ingreso')),
                ('egreso', models.TimeField(verbose_name='Horario de egreso')),
            ],
        ),
    ]
